void foo () throws Error {
}

void main () {
}
