# German message translation file for plpython
# Copyright (C) 2009 - 2018 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Peter Eisentraut <peter_e@gmx.net>, 2009 - 2018.
#
# Use these quotes: »%s«
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 11\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2018-05-07 00:38+0000\n"
"PO-Revision-Date: 2018-05-06 21:21-0400\n"
"Last-Translator: Peter Eisentraut <peter_e@gmx.net>\n"
"Language-Team: German <peter_e@gmx.net>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"

#: plpy_cursorobject.c:101
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor hat eine Anfrage oder einen Plan erwartet"

#: plpy_cursorobject.c:184
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor nimmt eine Sequenz als zweites Argument"

#: plpy_cursorobject.c:200 plpy_spi.c:211
#, c-format
msgid "could not execute plan"
msgstr "konnte Plan nicht ausführen"

#: plpy_cursorobject.c:203 plpy_spi.c:214
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Sequenz aus %d Argument erwartet, aber %d erhalten: %s"
msgstr[1] "Sequenz aus %d Argumenten erwartet, aber %d erhalten: %s"

#: plpy_cursorobject.c:352
#, c-format
msgid "iterating a closed cursor"
msgstr "Iteration mit einem geschlossenen Cursor"

#: plpy_cursorobject.c:360 plpy_cursorobject.c:426
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "Iteration mit einem Cursor in einer abgebrochenen Transaktionen"

#: plpy_cursorobject.c:418
#, c-format
msgid "fetch from a closed cursor"
msgstr "Lesen aus einem geschlossenen Cursor"

#: plpy_cursorobject.c:461 plpy_spi.c:409
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "Anfrageergebnis hat zu viele Zeilen, um in eine Python-Liste zu passen"

#: plpy_cursorobject.c:512
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "Schließen eines Cursors in einer abgebrochenen Subtransaktion"

#: plpy_elog.c:127 plpy_elog.c:128 plpy_plpymodule.c:559
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:142
#, c-format
msgid "unsupported set function return mode"
msgstr "nicht unterstützter Rückgabemodus für Funktion mit Mengenergebnis"

#: plpy_exec.c:143
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr "PL/Python unterstützt für Funktionen mit Mengenergebnis nur das Zurückgeben von einem Wert pro Aufruf."

#: plpy_exec.c:156
#, c-format
msgid "returned object cannot be iterated"
msgstr "zurückgegebenes Objekt kann nicht iteriert werden"

#: plpy_exec.c:157
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "PL/Python-Funktionen mit Mengenergebnis müssen ein iterierbares Objekt zurückgeben."

#: plpy_exec.c:171
#, c-format
msgid "error fetching next item from iterator"
msgstr "Fehler beim Auslesen des nächsten Elements vom Iterator"

#: plpy_exec.c:214
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "PL/Python-Prozedur hat nicht None zurückgegeben"

#: plpy_exec.c:218
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "PL/Python-Funktion mit Rückgabetyp »void« hat nicht None zurückgegeben"

#: plpy_exec.c:374 plpy_exec.c:400
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "unerwarteter Rückgabewert von Triggerprozedur"

#: plpy_exec.c:375
#, c-format
msgid "Expected None or a string."
msgstr "Erwartete None oder eine Zeichenkette."

#: plpy_exec.c:390
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "PL/Python-Funktion gab in einem DELETE-Trigger \"MODIFY\" zurück -- ignoriert"

#: plpy_exec.c:401
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Erwartete None, \"OK\", \"SKIP\" oder \"MODIFY\"."

#: plpy_exec.c:451
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() fehlgeschlagen, beim Einrichten der Argumente"

#: plpy_exec.c:455
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() fehlgeschlagen, beim Einrichten der Argumente"

#: plpy_exec.c:467
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "Funktion, die einen Record zurückgibt, in einem Zusammenhang aufgerufen, der Typ record nicht verarbeiten kann"

#: plpy_exec.c:684
#, c-format
msgid "while creating return value"
msgstr "beim Erzeugen des Rückgabewerts"

#: plpy_exec.c:909
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] wurde gelöscht, kann Zeile nicht ändern"

#: plpy_exec.c:914
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] ist kein Dictionary"

#: plpy_exec.c:941
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "Dictionary-Schlüssel auf Position %d in TD[\"new\"] ist keine Zeichenkette"

#: plpy_exec.c:948
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "in TD[\"new\"] gefundener Schlüssel »%s« existiert nicht als Spalte in der den Trigger auslösenden Zeile"

#: plpy_exec.c:953
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "Systemattribut »%s« kann nicht gesetzt werden"

#: plpy_exec.c:1011
#, c-format
msgid "while modifying trigger row"
msgstr "beim Ändern der Triggerzeile"

#: plpy_exec.c:1072
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "Abbruch einer Subtransaktion, die nicht beendet wurde, wird erzwungen"

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "in dieser Sitzung sind mehrere Python-Bibliotheken präsent"

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Nur eine Python-Hauptversion kann in einer Sitzung verwendet werden."

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr "nicht abgefangener Fehler bei der Initialisierung"

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr "konnte Modul »__main__« nicht importieren"

#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr "konnte globale Objekte nicht initialisieren"

#: plpy_main.c:399
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "PL/Python-Prozedur »%s«"

#: plpy_main.c:402
#, c-format
msgid "PL/Python function \"%s\""
msgstr "PL/Python-Funktion »%s«"

#: plpy_main.c:410
#, c-format
msgid "PL/Python anonymous code block"
msgstr "anonymer PL/Python-Codeblock"

#: plpy_plpymodule.c:192 plpy_plpymodule.c:195
#, c-format
msgid "could not import \"plpy\" module"
msgstr "konnte Modul »plpy« nicht importieren"

#: plpy_plpymodule.c:210
#, c-format
msgid "could not create the spiexceptions module"
msgstr "konnte das Modul »spiexceptions« nicht erzeugen"

#: plpy_plpymodule.c:218
#, c-format
msgid "could not add the spiexceptions module"
msgstr "konnte das Modul »spiexceptions« nicht hinzufügen"

#: plpy_plpymodule.c:286
#, c-format
msgid "could not generate SPI exceptions"
msgstr "konnte SPI-Ausnahmen nicht erzeugen"

#: plpy_plpymodule.c:454
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "konnte Argumente in plpy.elog nicht entpacken"

#: plpy_plpymodule.c:463
msgid "could not parse error message in plpy.elog"
msgstr "konnte Fehlermeldung in plpy.elog nicht parsen"

#: plpy_plpymodule.c:480
#, c-format
msgid "argument 'message' given by name and position"
msgstr "Argument »message« wurde durch Namen und Position angegeben"

#: plpy_plpymodule.c:507
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "»%s« ist ein ungültiges Schlüsselwortargument für diese Funktion"

#: plpy_plpymodule.c:518 plpy_plpymodule.c:524
#, c-format
msgid "invalid SQLSTATE code"
msgstr "ungültiger SQLSTATE-Code"

#: plpy_procedure.c:230
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "Triggerfunktionen können nur als Trigger aufgerufen werden"

#: plpy_procedure.c:234
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python-Funktionen können keinen Rückgabetyp %s haben"

#: plpy_procedure.c:312
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python-Funktionen können Typ %s nicht annehmen"

#: plpy_procedure.c:402
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "konnte PL/Python-Funktion »%s« nicht kompilieren"

#: plpy_procedure.c:405
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "konnte anonymen PL/Python-Codeblock nicht kompilieren"

#: plpy_resultobject.c:150 plpy_resultobject.c:176 plpy_resultobject.c:202
#, c-format
msgid "command did not produce a result set"
msgstr "Befehl hat keine Ergebnismenge erzeugt"

#: plpy_spi.c:60
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "zweites Argument von plpy.prepare muss eine Sequenz sein"

#: plpy_spi.c:104
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: Typname auf Position %d ist keine Zeichenkette"

#: plpy_spi.c:176
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute hat eine Anfrage oder einen Plan erwartet"

#: plpy_spi.c:195
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute nimmt eine Sequenz als zweites Argument"

#: plpy_spi.c:305
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan fehlgeschlagen: %s"

#: plpy_spi.c:347
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute fehlgeschlagen: %s"

#: plpy_subxactobject.c:122
#, c-format
msgid "this subtransaction has already been entered"
msgstr "diese Subtransaktion wurde bereits begonnen"

#: plpy_subxactobject.c:128 plpy_subxactobject.c:186
#, c-format
msgid "this subtransaction has already been exited"
msgstr "diese Subtransaktion wurde bereits beendet"

#: plpy_subxactobject.c:180
#, c-format
msgid "this subtransaction has not been entered"
msgstr "diese Subtransaktion wurde nicht begonnen"

#: plpy_subxactobject.c:192
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "es gibt keine Subtransaktion zu beenden"

#: plpy_typeio.c:591
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "konnte kein Modul für den »Decimal«-Konstruktor importieren"

#: plpy_typeio.c:595
#, c-format
msgid "no Decimal attribute in module"
msgstr "kein Attribut »Decimal« im Modul"

#: plpy_typeio.c:601
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "Umwandlung von numeric in Decimal fehlgeschlagen"

#: plpy_typeio.c:908
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "konnte Bytes-Darstellung eines Python-Objektes nicht erzeugen"

#: plpy_typeio.c:1056
#, c-format
msgid "could not create string representation of Python object"
msgstr "konnte Zeichenkettendarstellung eines Python-Objektes nicht erzeugen"

#: plpy_typeio.c:1067
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "konnte Python-Objekt nicht in cstring umwandeln: Python-Zeichenkettendarstellung enthält anscheinend Null-Bytes"

#: plpy_typeio.c:1176
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "Anzahl der Arraydimensionen überschreitet erlaubtes Maximum (%d)"

#: plpy_typeio.c:1180
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "konnte Sequenzlänge für Funktionsrückgabewert nicht ermitteln"

#: plpy_typeio.c:1183 plpy_typeio.c:1187
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "Arraygröße überschreitet erlaubtes Maximum"

#: plpy_typeio.c:1213
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "Rückgabewert von Funktion mit Array-Rückgabetyp ist keine Python-Sequenz"

#: plpy_typeio.c:1259
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr "falsche Länge der inneren Sequenz: hat Länge %d, aber %d wurde erwartet"

#: plpy_typeio.c:1261
#, c-format
msgid "To construct a multidimensional array, the inner sequences must all have the same length."
msgstr "Um ein mehrdimensionales Array zu konstruieren, müssen die inneren Sequenzen alle die gleiche Länge haben."

#: plpy_typeio.c:1340
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "fehlerhafte Record-Konstante: »%s«"

#: plpy_typeio.c:1341
#, c-format
msgid "Missing left parenthesis."
msgstr "Linke Klammer fehlt."

#: plpy_typeio.c:1342 plpy_typeio.c:1543
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr "Um einen zusammengesetzten Typ in einem Array zurückzugeben, geben Sie den zusammengesetzten Typ als ein Python-Tupel zurück, z.B. »[('foo',)]«."

#: plpy_typeio.c:1389
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "Schlüssel »%s« nicht in Mapping gefunden"

#: plpy_typeio.c:1390
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Um einen NULL-Wert in einer Spalte zurückzugeben, muss der Wert None mit einem nach der Spalte benannten Schlüssel in das Mapping eingefügt werden."

#: plpy_typeio.c:1443
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "Länge der zurückgegebenen Sequenz hat nicht mit der Anzahl der Spalten in der Zeile übereingestimmt"

#: plpy_typeio.c:1541
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "Attribut »%s« existiert nicht in Python-Objekt"

#: plpy_typeio.c:1544
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Um einen NULL-Wert in einer Spalte zurückzugeben, muss das zurückzugebende Objekt ein nach der Spalte benanntes Attribut mit dem Wert None haben."

#: plpy_util.c:35
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "konnte Python-Unicode-Objekt nicht in Bytes umwandeln"

#: plpy_util.c:41
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "konnte kodierte Zeichenkette nicht in Bytes umwandeln"
